[process_info]
name = "eldenring.exe"
window_name = "ELDEN RING"

[attributes.HeroHp]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x190, 0x0, 0x138]
type = "int"

[attributes.HeroMaxHp]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x190, 0x0, 0x13C]
type = "int"

[attributes.HeroFp]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x190, 0x0, 0x148]
type = "int"

[attributes.HeroMaxFp]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x190, 0x0, 0x150]
type = "int"

[attributes.HeroSp]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x190, 0x0, 0x154]
type = "int"

[attributes.HeroMaxSp]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x190, 0x0, 0x158]
type = "int"

[attributes.HeroAnimId]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x190, 0x18, 0x20]
type = "int"

[attributes.HeroAnimLength]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x190, 0x18, 0x24]
type = "float"

[attributes.HeroAnimSpeed]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x190, 0x28, 0x17C8]
type = "float"

[attributes.LocalPosX]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x190, 0x68, 0x70]
type = "float"

[attributes.LocalPosY]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x190, 0x68, 0x74]
type = "float"

[attributes.LocalPosZ]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x190, 0x68, 0x78]
type = "float"

[attributes.GlobalPosX]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x6C0]
type = "float"


[attributes.GlobalPosY]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x6C4]
type = "float"


[attributes.GlobalPosZ]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x6C8]
type = "float"


[attributes.AngleRad]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x6CC]
type = "float"


[attributes.MapId]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets = [0x10EF8, 0x0, 0x6D0]
type = "float"

[attributes.Gravity]
pattern = "48 8B 05 ?? ?? ?? ?? 48 85 C0 74 0F 48 39 88" 
offsets =  [0x10EF8, 0x0, 0x190, 0x68, 0x1D3]
type = "array"
length = 1

[attributes.NpcId]
method = "dll"
pattern = "48 8B 48 08 49 89 8D"
offsets = [0x28, 0x124]
type = "int"

[attributes.NpcHp]
method = "dll"
pattern = "48 8B 48 08 49 89 8D"
offsets = [0x190, 0x0, 0x138]
type = "int"